baseURL = 'https://willie169.github.io/blog/'
locale = 'en-us'
theme = 'blowfish'
title = "Willie169's Blog"

[params]
colorScheme = "noir"
    [params.author]
    name = "Willie Shen"
    image = "img/willie169.jpeg"
    headline = "ABC"
    bio = "DEF"
    links = [
      { github = "https://github.com/Willie169" },
      { mastodon = "https://mastodon.social/@willie_shen" },
      { matrix = "https://matrix.to/#/@willie169:matrix.org" },
      { rss = "https://willie169.github.io/blog/index.xml" },
    ]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[permalinks]
  [permalinks.page]
    posts = '/posts/:contentbasename/'
    # linux = '/posts/:contentbasename/'

 [menus]
  [[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 10

  [[menus.main]]
    name = "Posts"
    pageRef = "/posts"
    weight = 20

  [[menus.main]]
    name = "About"
    pageRef = "/about"
    weight = 30
